# Inserts a blank line between shell prompts
add_newline = true

# Move the directory to the second line
format = "$directory$character$line_break"
right_format = "$cmd_duration$all"

[line_break]
# disabled = true

[time]
disabled = false

[directory]
truncation_length = 8

[cmd_duration]
disabled = false
min_time = 0
