# Inserts a blank line between shell prompts
add_newline = false

# Move the directory to the second line
format = "$directory$character$line_break"
right_format = "$all"

[line_break]
# disabled = true

[time]
disabled = false

[directory]
truncation_length = 8
